---
memory: 1024
cpus: 2

# box: "centos/7"
box: "ubuntu/xenial64"

private_ip: 192.168.33.10

gitconfig: "~/.gitconfig"
ssh_private_key: "~/.ssh/id_rsa"
ssh_public_key: "~/.ssh/id_rsa.pub"

disable_default_share: true
shared_folders:
  -
    host_path: ./share
    # guest_path: /home/vagrant/share
    guest_path: /home/ubuntu/share
